apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  labels:
    app: landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      imagePullSecrets:
      - name: container-registry-dacodastrack-com-secret
      containers:
      - name: landing-page
        image: container-registry.dacodastrack.com/landing-page
        ports:
        - containerPort: 80
        imagePullPolicy: Always
